---
- name: check/configure pre-requisites
  hosts: all
  become: yes
  roles:
    - configure-os
    - remove-programs
    - install-programs

- name: Set up gluster
  hosts: manager, workers
  become: yes
  roles:
    - install-gluster

- name: Set up gluster shared volume
  hosts: manager
  become: yes
  roles:
    - create-shared-gluster-volume

- name: Mount gluster volume
  hosts: manager, workers
  become: yes
  roles:
    - finish-gluster-swarm-setup

- name: Install Docker
  hosts: manager, workers
  become: yes
  roles:
    - install-docker

- name: Start up Docker Swarm
  hosts: manager
  become: yes
  roles:
    - init-swarm

- name: Add workers to Swarm
  hosts: workers
  become: yes
  roles:
    - setup-swarm-worker

- name: Stand up basic Swarm stuff
  hosts: manager
  become: yes
  roles:
    - swarm-basics