---
- name: Install needed apps
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - glusterfs-server

- name: Start and enable glusterd
  shell: "systemctl start glusterd && systemctl enable glusterd"

- name: Create gluster root volume folder
  shell: "mkdir -p /gluster/swarm-vol"